### ISSUE TITLE
DLLNotLoaded

### ISSUE THREAD

**Issue by brooda** [severin-lemaignan/openni-python#13]
Hello, 

I am trying to run the code, but I am getting an error.

```
raise DLLNotLoaded("DLL is not loaded")
openni.utils.DLLNotLoaded: DLL is not loaded
```

I assumed that there is some problem with dependencies, so I installed openni2 library, but the problem still persists. 

Could you give some more info about prerequisites for that libary?

**Comment by hjmr** [comment]
@brooda Which platform are you trying to use OpenNI2? Please check if OpenNI2 DLL (filenames vary depending on platforms) is firmly located in the directory where the environment variable "OPENNI2_REDIST" points to.

**Comment by brooda** [comment]
I am trying to use it on Linux Ubuntu, DLL file is not the thing in this case.

**Comment by brooda** [comment]
I checked it and still there is the same problem.

**Comment by rokopi-byte** [comment]
This is what I do..

openni2.initialize(libpath)

where libpath is your OpenNI2 Redist folder.. does it help ?

**Comment by brooda** [comment]
@roccopietrini that helped. Thank you very much!
