### ISSUE TITLE
Recording from Orbbec Astra

### ISSUE THREAD

**Issue by roccopietrini** [severin-lemaignan/openni-python#5]
Hi,
I'm trying to record depth and color stream from Orbbec Astra model, that support OpenNI2 (using their package). Everything works, but I have to disconnect/reconnect the camera USB otherwise in the next recording the depth stream seems to be not generated by the camera, hence is not stored in the recording file. I suspect the problem is related to close/stop function I use for streams, recorder and device. I tried different combinations without any luck. Same problem both on Ubuntu 16.04 and Win10. You can have more details and the code used here: https://stackoverflow.com/questions/54342497/record-orbbec-astra-streams-with-python-and-openni2

Any hints?
Thank you

**Comment by rokopi-byte** [comment]
As you can see from stackoverflow I solved my issue.
