### ISSUE TITLE
Nite2.2 not working

### ISSUE THREAD

**Issue by pcp16** [severin-lemaignan/openni-python#6]
Hi using the pypi version but cannot get Nite2 (I have Nite2.2) to work. Using the example in the README.md, it always goes through the `except` path:

```
import sys
from openni import openni2, nite2, utils

openni2.initialize()
nite2.initialize()

dev = openni2.Device.open_any()

try:
    userTracker = nite2.UserTracker(dev)
except utils.NiteError as ne:
    logger.error("Unable to start the NiTE human tracker. Check "
                 "the error messages in the console. Model data "
                 "(s.dat, h.dat...) might be inaccessible.")
    sys.exit(-1)
```

**Comment by pcp16** [comment]
Ok, got it working from the fork by hjmr: https://github.com/hjmr/openni-python

**Comment by severin-lemaignan** [comment]
Thanks @pcp16 for pointing out @hjmr changes. I've merged them in this repo, and I'll update ASAP the pip version.

**Comment by ccl-private** [comment]
hi, I still meet this problem. I download the latest master branch and put them into my python project. color_stream and depth_stream work well. But nite2.UserTracker(dev) failed, try-catching error "NiteStatus.NITE_STATUS_ERROR".
My nite version is 2.2, how to fix this?
I also noticed the message in try-except, "(s.dat, h.dat...) might be inaccessible." I find the two .dat files in .../Redist/NiTE2/. Could it be a configuration error on my part?

**Comment by hjmr** [comment]
I don't know if this will be effective but please check "DataDir" in "General" section of .../Redist/NiTE.ini which must specify the directory where the two .dat files is located. It looks like you can use a relative path there but I've never succeeded. I recommend to use an absolute path. Hope it helps.

**Comment by ccl-private** [comment]
@hjmr It seems that something else is wrong. I tried an absolute path, but, still, the same error.
My RGBD cameras are ASUS Xtion PRO LIVE and Orbbec Astra. Any ideas?

**Comment by hjmr** [comment]
@ccl-private I checked with Structure Sensor from Occipital and Intel D435 on macOS. But I don't think this problem is relating to what camera you are using. What OS did you try on?

**Comment by ccl-private** [comment]
@hjmr My os is Ubuntu 18.06.

**Comment by ccl-private** [comment]
I tried again on another computer, ubuntu18 too, got a different error.
![Screenshot from 2019-07-07 14-39-01](https://user-images.githubusercontent.com/36214675/60765057-9547f300-a0c6-11e9-81a0-90f554d8a245.png)
I am sure I have libNiTE2.so file in that directory.
![Screenshot from 2019-07-07 14-39-19](https://user-images.githubusercontent.com/36214675/60765068-bc062980-a0c6-11e9-87f8-ec08844d5471.png)

My NiTE2 downloaded from [http://cvrlcode.ics.forth.gr/web_share/OpenNI/NITE_SDK](url).

**Comment by ccl-private** [comment]
Hi, @hjmr. my problem is solved at "https://github.com/severin-lemaignan/openni-python/issues/4".
It is because NiTE2 cannot find openni2.
