### ISSUE TITLE
Unexposed get_user_map() function

### ISSUE THREAD

**Issue by pcp16** [severin-lemaignan/openni-python#8]
Hi,

Following the UserView example (`UserView/Viewer.cpp`) example that comes with Nite2.2, I can see there is a way to get the labelled user map from the `UserTrackerFrame` using:

```cpp
nite::UserTrackerFrameRef userTrackerFrame;
nite::Status rc = m_pUserTracker->readFrame(&userTrackerFrame);
depthFrame = userTrackerFrame.getDepthFrame();
const nite::UserMap& userLabels = userTrackerFrame.getUserMap();
```

Similarly, on python I am trying to replicate that particular bit by doing:

```python
frame = userTracker.read_frame()
depth = np.frombuffer(frame.get_depth_frame().get_buffer_as_uint16(), dtype=np.uint16)
depth = depth.reshape(480, 640)
visual_depth = np.uint8((depth/4500.)*255.)
visual_depth = cv2.cvtColor(visual_depth, cv2.COLOR_GRAY2BGR)
# user_map = frame.get_user_map()
```
However, there is no `get_user_map()` function in `frame`, which is of `UserTrackerFrame` type. Is this a bug (i.e. non-exposure of the get_user_map function) or is there any other way to proceed?

**Comment by hjmr** [comment]
I don't whether it's exactly what you want or not but `UserTrackerFrame` has `userMap` attribute which seems to be able to use instead. The following code works on my Mac.
```
frame = userTracker.read_frame()
depth_frame = frame.get_depth_frame()
depth_data = np.frombuffer(depth_frame.get_buffer_as_uint16(), dtype=np.uint16)
depth_data = depth_data.reshape(depth_frame.height, depth_frame.width)
visual_depth = np.uint8((depth_data/4500.)*255.)
visual_depth = cv2.cvtColor(visual_depth, cv2.COLOR_GRAY2BGR)
user_map = frame.userMap
```
Hope this helps.

**Comment by pcp16** [comment]
Correct, this works fine. `visual_users` now shows a color map with different colors for each user:

```python
COLORS = [(0, 0, 255), (0, 128, 255), (0, 255, 255), (0, 255, 128),
      (0, 255, 0), (128, 255, 0), (255, 255, 0), (255, 128, 0)]
user_map = frame.userMap
user_labels = np.ctypeslib.as_array(user_map.pixels, shape=(user_map.width * user_map.height,))
user_labels = user_labels.reshape(user_map.height, user_map.width)
visual_users = np.zeros((user_map.height, user_map.width, 3), dtype=np.uint8)
for i in range(len(COLORS)):
    visual_users[user_labels == i + 1] = COLORS[i]
```

**Comment by severin-lemaignan** [comment]
@pcp16 if you have a simple complete example, please add it to the README (ideally, with a screenshot). It will surely be useful to other users!
